/* Spawn Mikala in the Belching Dragon 
AR4809

 half-orc
(doesn't exist in BG1)
*/




IF 
	Gender(Player1,FEMALE)
	Race(Player1,HALFORC)
	!Exists("M3Mikala")
	!Dead("M3Mikala") 
	Global("RE1_MikalaSpawn","GLOBAL",0)
	GlobalGT("CHAPTER","GLOBAL",%tutu_chapter_2%) //after clearing the Nashkel mines)
THEN
	RESPONSE #100
		SetGlobal("RE1_MikalaSpawn","GLOBAL",1)
		CreateCreature("M3Mikala",[735.410]%FACE_5%) 
	Continue()
END