IF 
Global("TICamryn","GLOBAL",0)
Global("TICBOOK13_Gone","%WBaldursGate_RagefastsHouse%",0)  //you need a check variable, or the script block will be true always and block everything beneath it

THEN
RESPONSE #100
ActionOverride("Container3",DestroyItem("TITOME13")) //unfortunately, you need the container name, yes. And don't get discouraged if it seem not to work the first time
SetGlobal("TICBOOK13_Gone","%WBaldursGate_RagefastsHouse%",1)
Continue()
END