IF 
Global("TICamryn","GLOBAL",0)
Global("TICBOOK12_Gone","%NBaldursGate_RamazithsTower_L6%",0)  //you need a check variable, or the script block will be true always and block everything beneath it

THEN
RESPONSE #100
ActionOverride("Container8",DestroyItem("TITOME12")) //unfortunately, you need the container name, yes. And don't get discouraged if it seem not to work the first time
SetGlobal("TICBOOK12_Gone","%NBaldursGate_RamazithsTower_L6%",1)
Continue()
END