IF 
Global("TICamryn","GLOBAL",0)
Global("TICBOOK10_Gone","%CloakwoodMines_L4%",0)  //you need a check variable, or the script block will be true always and block everything beneath it

THEN
RESPONSE #100
ActionOverride("Container7",DestroyItem("TITOME10")) //unfortunately, you need the container name, yes. And don't get discouraged if it seem not to work the first time
SetGlobal("TICBOOK10_Gone","%CloakwoodMines_L4%",1)
Continue()
END