IF 
Global("TICamryn","GLOBAL",0)
Global("TICBOOK03_Gone","%Beregost_LandrinsHouse%",0)  //you need a check variable, or the script block will be true always and block everything beneath it



THEN
RESPONSE #100
ActionOverride("Container2",DestroyItem("TITOME03")) //unfortunately, you need the container name, yes. And don't get discouraged if it seem not to work the first time
SetGlobal("TICBOOK03_Gone","%Beregost_LandrinsHouse%",1)
Continue()
END