/* Activate: Sharteel notices girdle of gender on PC , F-> M */
IF %BGT_VAR%
Global("RE1_GirdleSharteelPCDidIt","GLOBAL",0)
HasItemEquiped("%tutu_var%BELT05",Player1)
Gender(Player1,MALE)
InParty(Myself)
Detect(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID)
%CombatCounter_0%
!See([ENEMY])
THEN
RESPONSE #100
SetGlobal("RE1_GirdleSharteelPCDidIt","GLOBAL",1)
END

/* Initiate: Sharteel/PC girdle talk */
IF %BGT_VAR%
Global("RE1_GirdleSharteelPCDidIt","GLOBAL",1)
InParty(Myself)
Detect(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID)
%CombatCounter_0%
!See([ENEMY])
THEN
RESPONSE #100
StartDialogueNoSet(Player1)
END