/* Activate: Imoen notices girdle of gender on PC */
IF %BGT_VAR%
Global("RE1_GirdleImoenPCDidIt","GLOBAL",0)
HasItemEquiped("%tutu_var%BELT05",Player1)
InParty(Myself)
Detect(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID)
%CombatCounter_0%
!See([ENEMY])
THEN
RESPONSE #100
SetGlobal("RE1_GirdleImoenPCDidIt","GLOBAL",1)
END

/* Initiate: Imoen/PC girdle talk */
IF %BGT_VAR%
Global("RE1_GirdleImoenPCDidIt","GLOBAL",1)
HasItemEquiped("%tutu_var%BELT05",Player1)
InParty(Myself)
Detect(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID)
%CombatCounter_0%
!See([ENEMY])
THEN
RESPONSE #100
StartDialogueNoSet(Player1)
END